#include "drivers/oled_display.h"

#include <U8g2lib.h>
#include <Wire.h>

#include "app/config.h"
#include "assets/face_bitmaps.h"

namespace yappl {
namespace {

// HiLetgo's 1.5 inch 128x128 OLED uses an SH1107 controller. This panel maps
// correctly with U8g2's zero-offset Seeed 128x128 variant.
U8G2_SH1107_SEEED_128X128_F_HW_I2C g_oled(U8G2_R0, U8X8_PIN_NONE);

// Physical display dimensions. Generated face bitmaps are smaller and centered
// inside this 128x128 area.
constexpr uint8_t kDisplayWidth = 128;
constexpr uint8_t kDisplayHeight = 128;

void drawWifiIcon(bool connected, bool inverted) {
  // Keep the icon in the upper-right corner and small enough that it does not
  // compete with the character animation.
  constexpr int16_t x = 114;
  constexpr int16_t y = 4;

  // On inverted frames the background is white, so draw the icon black.
  g_oled.setDrawColor(inverted ? 0 : 1);

  // Dot plus three rising bars reads well at tiny monochrome size.
  g_oled.drawDisc(x + 2, y + 8, 1);
  g_oled.drawVLine(x + 5, y + 6, 3);
  g_oled.drawVLine(x + 8, y + 4, 5);
  g_oled.drawVLine(x + 11, y + 2, 7);

  if (!connected) {
    // A diagonal slash means "Wi-Fi not connected" while preserving the same
    // base icon shape.
    g_oled.drawLine(x, y + 1, x + 13, y + 10);
  }

  g_oled.setDrawColor(1);
}

void drawBackendIcon(bool connected, bool inverted) {
  // Two interlocking links distinguish backend connectivity from Wi-Fi.
  if (!connected) {
    return;
  }

  constexpr int16_t x = 101;
  constexpr int16_t y = 5;
  g_oled.setDrawColor(inverted ? 0 : 1);
  g_oled.drawRFrame(x, y, 7, 5, 2);
  g_oled.drawRFrame(x + 5, y + 3, 7, 5, 2);
  g_oled.setDrawColor(1);
}

void drawUploadIcon(bool uploading, bool inverted) {
  if (!uploading) {
    return;
  }

  constexpr int16_t x = 92;
  constexpr int16_t y = 4;
  g_oled.setDrawColor(inverted ? 0 : 1);
  g_oled.drawVLine(x + 3, y + 2, 7);
  g_oled.drawLine(x, y + 5, x + 3, y + 2);
  g_oled.drawLine(x + 6, y + 5, x + 3, y + 2);
  g_oled.drawHLine(x, y + 10, 7);
  g_oled.setDrawColor(1);
}

void drawClock(bool timeSynced, uint8_t hour, uint8_t minute, bool inverted) {
  // Small top-left clock. "--:--" means Wi-Fi may be connected but NTP time has
  // not been fetched yet.
  char text[6] = "--:--";
  if (timeSynced) {
    snprintf(text, sizeof(text), "%02u:%02u", hour, minute);
  }

  g_oled.setDrawColor(inverted ? 0 : 1);
  g_oled.setFont(u8g2_font_5x8_tf);
  g_oled.drawStr(2, 10, text);
  g_oled.setDrawColor(1);
}

}  // namespace

bool OledDisplay::begin() {
  // Use configured I2C pins rather than Arduino board defaults.
  Wire.begin(AppConfig::oledSdaPin, AppConfig::oledSclPin);
  // 400 kHz keeps animation reasonably responsive. If the OLED glitches, try
  // reducing this to 100000.
  Wire.setClock(400000);

  // U8g2 expects the 8-bit I2C address form, so shift the 7-bit address left.
  g_oled.setI2CAddress(AppConfig::oledAddress << 1);
  g_oled.begin();
  g_oled.setContrast(180);
  clear();
  return true;
}

void OledDisplay::clear() {
  // Full-buffer mode: clear RAM buffer first, then send it to the OLED.
  g_oled.clearBuffer();
  g_oled.sendBuffer();
}

void OledDisplay::drawFaceFrame(const FaceFrame &frame,
                                bool wifiConnected,
                                bool backendConnected,
                                bool audioUploading,
                                bool timeSynced,
                                uint8_t hour,
                                uint8_t minute) {
  // Convert frame metadata into the actual bitmap bytes to draw.
  const FaceBitmap &bitmap = faceBitmap(frame.bitmapId);
  // Center the face, then apply per-frame offsets for shaking/dancing.
  const int16_t x = (kDisplayWidth - bitmap.width) / 2 + frame.xOffset;
  const int16_t y = (kDisplayHeight - bitmap.height) / 2 + frame.yOffset;

  g_oled.clearBuffer();
  if (frame.invert) {
    // Inverted frames draw a filled white background, then draw the bitmap as
    // black pixels. Most current frames are non-inverted.
    g_oled.drawBox(0, 0, kDisplayWidth, kDisplayHeight);
    g_oled.setDrawColor(0);
  }
  // drawXBMP expects the 1-bit byte layout generated by face_bitmaps.cpp.
  g_oled.drawXBMP(x, y, bitmap.width, bitmap.height, bitmap.data);
  if (frame.invert) {
    g_oled.setDrawColor(1);
  }
  drawClock(timeSynced, hour, minute, frame.invert);
  drawUploadIcon(audioUploading, frame.invert);
  drawBackendIcon(backendConnected, frame.invert);
  drawWifiIcon(wifiConnected, frame.invert);
  g_oled.sendBuffer();
}

}  // namespace yappl
